Update default version of crane from 0.14.0 to 0.19.0
Since I just tried to use `crane copy --all-tags` with the version installed
by the `setup-tools` action, however, it failed with:

```
Error: unknown flag: --all-tags
```

It turns out that feature was added in 0.15.0 in May 2023, but that
version is still newer than the version installed by this action.

Whilst I can manually override the version myself, it seems we should
update the default version to prevent others from running into
similar footguns.

https://github.com/google/go-containerregistry/compare/v0.14.0...v0.19.0

Signed-off-by: Ed Morley <501702+edmorley@users.noreply.github.com>